services:
  weather-app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    ports:
      - "5000:5000"   # mapped to avoid Jenkins port conflict
    environment:
      - API_KEY=${API_KEY}
    restart: unless-stopped
